### ISSUE TITLE
Confirm API - DONE

### ISSUE THREAD

**Issue by MannyChita** [alisonwood29/group_project_educational_app#4]

**Comment by MannyChita** [comment]
http://collection.sciencemuseum.org.uk - Science Museum History of Tech API

**Comment by GraemeHBrown** [comment]
[selected_objects.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a9aeec501903c0011754234/125516c66e82c728ace21e0d46fb9196268197ac8bd6b041ae58f3803a046b313916ac217586f76ae5002e0056564bfd175a0e11aafed87da6b63d238b550cefd0654d68d47f40f2ecdd42e64bef62994597b7bb804dc5ea3d24e7888d483a1a0c109bb2.xlsx)

**Comment by GraemeHBrown** [comment]
Added excel sheet with objects which will be used in the initial timeline.
