### ISSUE TITLE
Proto Persona

### ISSUE THREAD

**Issue by MannyChita** [alisonwood29/group_project_educational_app#7]

**Comment by GiuseppeIbba** [comment]
![ProtoPersona.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a9964d22bba6c0011e26c3e/125516c66e82c728ace21e0d46d88695378db3ac9dfab04da51fbcd6395428792c07b7692ac7b629e61b2e00095d1ff9175f0e12fcf98878a7bf3b728b5419f1c32f0e2a92624cf5f2d75dad0ba821834584b3be8a4bc7e0392ce68d884d2c53.png)
